draft: add sbt usage page
scala-text/scala_text pull request #1016
Opened 2022-09-16 14:12 UTC by i10416

sbt の使い方を最低限(例: Scala バージョンの指定やライブラリの追加方法)書いてある方が初心者に優しいのではないか？と思って追加した.

また、詳細を管理するのは手間なので以下の一文を冒頭に入れた.

> 以下ではsbtの基本的な機能を紹介しますが、詳細は[公式ドキュメント](https://www.scala-sbt.org/1.x/docs/ja/Getting-Started.html)を参照してください。

close #1012

2022-09-16 22:22 UTC, xuwei-k commented
textlint大量に落ちてる

2022-09-16 22:23 UTC, xuwei-k commented on src/sbt-usage.md
> +- ライブラリをインストールしたりライブラリを公開したりするパッケージマネージャーとして機能
```suggestion
- ライブラリをインストールしたりライブラリを公開したりするパッケージマネージャーとしての機能
```

2022-09-16 22:25 UTC, xuwei-k commented on src/sbt-usage.md
> +sbt コンソールから `++2.13.8 <sbt command>` とすることで Scala のバージョンを指定して sbt のコマンドを実行したり、
コマンドっていう用語、sbtの公式のCommandやTaskとしてのコマンドとの違いがややこしいような

2022-09-16 22:26 UTC, xuwei-k commented
そもそも根本的に前もどこかで何度か書いたけど、sbt自体は公式ページ参照してもらって、足りないとかわかりずらいなら、そっちを充実させればいい気がするから、ここに追加するのはあまり賛成ではないなぁ

2022-09-16 22:28 UTC, xuwei-k commented on src/sbt-usage.md
> +`"パッケージのネームスペース" %% "パッケージ名" % "バージョン"` という形式です.
ネームスペースやパッケージ名というのは用語として微妙な気が

2022-09-16 22:29 UTC, xuwei-k commented on src/sbt-usage.md
> +import cats.implicits._
- https://github.com/typelevel/cats/issues/4138#issuecomment-1048487958

2022-09-16 22:30 UTC, xuwei-k commented on src/sbt-usage.md
> +        "log4j" % "log4j" % "1.2.17"
例とはいえ脆弱性で話題になったlog4jの1系は… 🤔

2022-09-16 22:31 UTC, xuwei-k commented on src/sbt-usage.md
> +### JVM以外のプラットフォームからライブラリを利用する
plugins.sbtのaddSbtPluginの記述がないような

2022-09-16 22:33 UTC, xuwei-k commented on src/sbt-usage.md
> +リリースされるアプリケーションやライブラリには含まれません. JavaScript の package.json に含まれる
Javaの記述は消すけどJSの記述は例に出すのは若干疑問が残るが🤔 
まぁ他にもっと良い例がないならいいか？

2022-09-16 22:34 UTC, xuwei-k commented on src/sbt-usage.md
> +これで ターミナル または sbt コンソールから scalafmt, scalafmtSbt, scalafmtCheck, scalafmtAll などのコマンドが使えるようになります.
sbt コンソール、
というのもconsoleというREPL起動するやつがあってそれとの区別がややこしいから、用語の扱いしっかりした方が。
あれはshellだっけ、なんだっけ

2022-09-16 22:36 UTC, xuwei-k commented on src/sbt-usage.md
> +        "com.typelevel" %% "cats-core" % "2.7.0"
インデントが

2022-09-16 22:37 UTC, xuwei-k commented on src/sbt-usage.md
> +```scala
ここはmdocで書くか？

2022-09-16 22:38 UTC, xuwei-k commented
catsどうせなら最新版の方が

2022-09-17 11:20 UTC, xuwei-k commented on src/sbt-usage.md
> +ライブラリをビルドします.
そこまで応用向けな話でもないけど、Scala初学者が学ぶため、という方向性のテキストなら、この話どの程度入れるべきか？というと微妙か・・・？ 🤔

2022-09-17 11:20 UTC, xuwei-k commented on src/sbt-usage.md
> +`++<sbt command>` とすることで crossScalaVersions に指定したすべての Scala バージョンでコマンドを実行したりすることができます.
`++<sbt command>` は `+<sbt command>` の間違い？

2022-09-17 11:22 UTC, xuwei-k commented on src/sbt-usage.md
> +        "log4j" % "log4j" % "1.2.17"
log4j、(mavenの用語だと)groupIdとartifactIdが同じなのも、例としてややこしいか？ 🤔

2022-09-17 11:41 UTC, xuwei-k commented
そもそも、もしsbtの記述を今より入れるにしても、何をどのくらい入れるか？を結構考えないと、統一性というか「初学者向け」という観点からすると色々微妙になりそうな気がするんだよなぁ。

「これを入れるならこっちも入れるべきでは？」

となって、かといって、とりとめなく追加していけばいいものでもないし。
メンテコスト上がる and 追加し過ぎたら結局初学者にとってどれが重要なのか？が、(相当工夫して書かない限り)わかりづらくなってデメリット増える、などがあり

2022-09-17 12:12 UTC, xuwei-k commented on src/sbt-usage.md
> +### JVM以外のプラットフォームからライブラリを利用する
もう少し言いたいこと足しておくと

- 本当に最低限とはいえ、とりあえず書いてある通りにやるとjsやnativeで動くサンプルを作れる記述にするべき？、なら、plugins.sbtにjsやnativeの記述例も追加する(version管理するなら、その分メンテコスト上がるが)
  - あるいは、あえてその部分を省略したことを明記して詳細は公式見てね、としてリンク貼る？
- とにかく「jsやnative向けのpluginもあるよ」という紹介というか雰囲気を掴むだけにするなら、逆にもっと簡素にする？
- その他？ 🤔

2022-09-17 16:24 UTC, kmizu commented
@xuwei-k 実はこの辺り、先週のscala_text もくもく会＠Discordでなんとなく決まったことなんで経緯書いておきます：
- @i10416 さんからsbtの記述を追加してみてはどうかという提案
- @kmizu が「本格的なのはsbt公式ページに任せて、薄い感じで使い方だけ書くのはどうか」という感じで @i10416 さんにアサイン
- @i10416 さんがプルリク作成
の
おっしゃる通り、

> 何をどのくらい入れるか？

も重要だとは思いますが、深く決めずに見切り発車した面があります。「sbtをインストールする」というページは既にあるわけだし、

- build.sbtの基本的な書き方
  - scalaVersion, version, name, organizationとか
- libraryDependenciesの書き方（追加の仕方）

くらいは書いておいてもこれ以上あんまり変わらないだろうし、いいのかなと思ってます。

2022-09-17 19:08 UTC, xuwei-k commented
あとここに足してない https://github.com/scala-text/scala_text/blob/f8dd77cb517ab43528d354021d39938f8d425367/src/SUMMARY.md

2022-09-18 15:00 UTC, kmizu commented
@xuwei-k 承知しました。最低限、
- 決まったこと
- 議論になったこと
辺りの一覧は書くようにしますね。

2022-09-21 17:33 UTC, i10416 commented on src/sbt-usage.md
> +`"パッケージのネームスペース" %% "パッケージ名" % "バージョン"` という形式です.
ですね...訂正します

```suggestion
`"パッケージのグループID" %% "アーティファクトID" % "バージョン"` という形式です.
```

2022-09-21 17:41 UTC, i10416 commented on src/sbt-usage.md
> +リリースされるアプリケーションやライブラリには含まれません. JavaScript の package.json に含まれる
自分の観測範囲の問題かもしれませんが Java よりも Python や JavaScript を使っている方が多いのでユーザー数の多い言語のものを例にあげました. Python は requirements.txt や poetry などいろいろあるので js を例にしました.

2022-09-21 17:41 UTC, i10416 commented on src/sbt-usage.md
> +これで ターミナル または sbt コンソールから scalafmt, scalafmtSbt, scalafmtCheck, scalafmtAll などのコマンドが使えるようになります.
あー、確かに...
コマンドを実行するのは sbt shell ですね

2022-09-21 17:43 UTC, i10416 commented on src/sbt-usage.md
> +`++<sbt command>` とすることで crossScalaVersions に指定したすべての Scala バージョンでコマンドを実行したりすることができます.
ですね🙄

2022-09-21 17:44 UTC, i10416 commented
> そもそも根本的に前もどこかで何度か書いたけど、sbt自体は公式ページ参照してもらって、足りないとかわかりずらいなら、そっちを充実させればいい気がするから、ここに追加するのはあまり賛成ではない

これはおおむね同意ですがライブラリの追加方法など基本的なことは書いておいてもいいかな？と思いました. 

また、このPRでは1ページ追加して書きましたが適当な場所があるなら既存のページにもう少し簡潔にしようかと思っていますがどうでしょうか.
（文章の流れを壊さずsbtの記述をいい感じに入れられるところが見当たらなかったので質問しました）

2022-09-21 17:47 UTC, i10416 commented on src/sbt-usage.md
> +### JVM以外のプラットフォームからライブラリを利用する
> plugins.sbtのaddSbtPluginの記述がないような
 
入れるべきか迷って書かなかったのですが、簡潔にして公式ドキュメントに流す方がメンテしやすくてよさそうですね

ただ、日本語で書かれているテキストがあるという点が初心者からしたらうれしいかも？とは思いました.

2022-09-21 17:49 UTC, i10416 commented on src/sbt-usage.md
> +sbt コンソールから `++2.13.8 <sbt command>` とすることで Scala のバージョンを指定して sbt のコマンドを実行したり、
```suggestion
sbt シェルから `++2.13.8 <sbt command>` とすることで Scala のバージョンを指定して sbt のコマンドを実行したり、
```

2022-09-21 17:51 UTC, i10416 commented on src/sbt-usage.md
> +`++<sbt command>` とすることで crossScalaVersions に指定したすべての Scala バージョンでコマンドを実行したりすることができます.
```suggestion
`+<sbt command>` とすることで crossScalaVersions に指定したすべての Scala バージョンでコマンドを実行したりすることができます.
```

2022-09-21 17:51 UTC, i10416 commented on src/sbt-usage.md
> +これで ターミナル または sbt コンソールから scalafmt, scalafmtSbt, scalafmtCheck, scalafmtAll などのコマンドが使えるようになります.
```suggestion
これで ターミナル または sbt シェルから scalafmt, scalafmtSbt, scalafmtCheck, scalafmtAll などのコマンドが使えるようになります.
```

2022-09-22 01:52 UTC, xuwei-k commented
textlintはこういうの100カ所以上？怒られてる


>  句読点には全角の「、」と「。」を使います。和文の句読点としてピリオド(.)とカンマ(,)を使用しません。  jtf-style/1.2.1.句点(。)と読点(、)
    7:19  ✓ error  和文の句読点としてはピリオドを使用しません。                                                        jtf-style/4.1.3.ピリオド(.)、カンマ(,)
    9:8   ✓ error  原則として、全角文字と半角文字の間にスペースを入れません。                                          jtf-style/3.1.1.全角文字と半角文字の間
    9:18  ✓ error  半角のかっこ()が使用されています。全角のかっこ（）を使用してください。                              jtf-style/4.3.1.丸かっこ（）

2022-09-22 04:01 UTC, i10416 commented on src/sbt-usage.md
> +        "log4j" % "log4j" % "1.2.17"
(良くも悪くも)知名度高い Java のライブラリだとこれかなって思いましたが、”groupIdとartifactIdが同じなのも...” を考慮すると他のライブラリの方がいいですね　

2022-09-22 04:05 UTC, i10416 commented on src/sbt-usage.md
> +### JVM以外のプラットフォームからライブラリを利用する
ひとまず、ライブラリを追加する際に `%%` と `%%%`があることを言及するためにscalajs の例は残します.

2022-09-22 04:17 UTC, i10416 commented on src/sbt-usage.md
> +ライブラリをビルドします.
他の言語の経験者で Scala 初学者の場合、アプリケーションでなくライブラリを書くことにも関心がある方がいるのでは？と思ったのでクロスビルドについて記述しました.

2022-09-22 04:22 UTC, i10416 commented
> textlintはこういうの100カ所以上？怒られてる

すみません. とりあえず書いてみて、フィードバック次第で既存のページのどこかのセクションに追加するか、別のページにするか、そもそも書かないか検討して、書くならその際に清書すればいいかな、と思っていて雑になりました.

2022-09-22 13:40 UTC, kmizu commented on src/sbt-usage.md
> +        "com.typelevel" %% "cats-core" % "2.7.0"
この場合だと、 

```scala
  Seq(
    "com.typelevel" %% "cats-core" % "2.7.0"
  )
```

になってて欲しいみたいな話ですか？（インデント幅の話？）

2022-09-22 13:45 UTC, kmizu commented on src/sbt-usage.md
> +        "log4j" % "log4j" % "1.2.17"
知名度が高いJavaライブラリだとなんでしょうね……。Webアプリ系だとMockitoとか？

https://github.com/mockito/mockito

たとえば、

```
"org.mockito" % "mockito-core" % "3.0.0" % Test
```

とか。

2022-09-22 13:47 UTC, kmizu commented on src/sbt-usage.md
> +### JVM以外のプラットフォームからライブラリを利用する
@i10416 ちょい難しいところかと思うんですが、最低限と割り切るなら需要が低いjsやnativeは切り捨てて、そっちは公式ドキュメント参照してね、がいいのかなと考えてます。`%%%` に言及したい積極的な理由ってあったりするでしょうか？

2022-09-22 13:51 UTC, kmizu commented on src/sbt-usage.md
> +リリースされるアプリケーションやライブラリには含まれません. JavaScript の package.json に含まれる
他言語の経験があること前提なら一番身近であろうJSを例に出すのも……まあありかもです。あるいは、とりあえず「こういうもんです」とするのも手かもとは思います。

2022-09-22 13:54 UTC, kmizu requested changes
@i10416 些細な指摘はどちらでもいいですが、ミスっぽいものだけ直してもらえればOKです。

2022-09-23 00:06 UTC, xuwei-k commented on src/sbt-usage.md
> +      "com.typelevel" %%% "cats-core" % "2.7.0"
```suggestion
      "com.typelevel" %%% "cats-core" % "2.8.0"
```

2022-09-23 00:06 UTC, xuwei-k commented on src/sbt-usage.md
> +        "com.typelevel" %% "cats-core" % "2.7.0",
```suggestion
        "com.typelevel" %% "cats-core" % "2.8.0",
```

2022-09-23 00:07 UTC, xuwei-k commented on src/sbt-usage.md
> +    crossScalaVersions := Seq("2.13.8","3.2.0")
```suggestion
    crossScalaVersions := Seq("2.13.8", "3.2.0")
```

2022-09-23 02:04 UTC, xuwei-k commented
> あとここに足してない https://github.com/scala-text/scala_text/blob/f8dd77cb517ab43528d354021d39938f8d425367/src/SUMMARY.md


https://github.com/scala-text/scala_text#honkit%E3%81%A7%E7%89%B9%E5%88%A5%E8%A6%96%E3%81%95%E3%82%8C%E3%82%8B%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

> summary: 本のページ遷移情報に利用される
> summaryを更新しないとページを追加しても本に反映されないので注意が必要。

2022-09-23 07:50 UTC, xuwei-k commented on src/sbt-usage.md
> +  )
```suggestion
scalaVersion := "3.2.0"
```

今後も複数projectの説明する気がない and 初心者向けなら、全部こっちで書く、というのもありか？ 🤔

2024-02-28 12:04 UTC, kmizu commented
こちら議論が停滞したままなのでいったんcloseします。またopenが必要な場合は別途議論するということで 🙏

2024-02-28 12:04 UTC, closed without merging