955: クラスの継承の部分の説明を整理
scala-text/scala_text pull request #981
Opened 2022-08-01 13:00 UTC by rinotc

2022-08-01 13:01 UTC, rinotc commented on src/class.md
> +Scalaのクラスは、他の多くのオブジェクト指向言語と同様に、継承することができます。
Javaを明示しない。

2022-08-01 13:10 UTC, rinotc commented on src/class.md
> +例えば、Javaでは実装継承が1つだけに限定されています。
ここはないと伝わらなそうなので残しました。

2022-08-01 13:10 UTC, rinotc commented on src/class.md
> +※「トレイト名」はここでは使われませんが、後で出てくるトレイトの節で説明を行います。
前部分の説明と後ろ部分の説明がわかりづらかったので注釈的に記載して見ました。

2022-08-01 13:10 UTC, rinotc commented on src/class.md
> +このような仕組みのないJavaのような言語ではしばしば、気付かずに既存のメソッドをオーバーライドするつもりで新しいメソッドを定義してしまうというミスがありますが、
仕組みのない言語が何か消しちゃうと分からなくなるので消さず。

2022-08-01 15:42 UTC, rinotc commented on src/class.md
> +継承のはたらきはJavaのクラスと同様ですが、 既存のメソッドをオーバーライドするときは`override`キーワードを使わなければならない点が異なります。
ここどう書くか悩むます。

2022-08-01 23:34 UTC, xuwei-k commented on src/class.md
> +このような仕組みのないJavaのような言語ではしばしば、気付かずに既存のメソッドをオーバーライドするつもりで新しいメソッドを定義してしまうというミスがありますが、
直すとしても別pull reqでいいけど、Javaに `@Override` アノテーションあるから、この記述若干語弊があるな 🤔

2022-08-02 00:50 UTC, kmizu commented on src/class.md
> +Scalaのクラスは、他の多くのオブジェクト指向言語と同様に、継承することができます。
これはそんな感じでグーです。

2022-08-02 00:52 UTC, kmizu commented on src/class.md
> +このような仕組みのないJavaのような言語ではしばしば、気付かずに既存のメソッドをオーバーライドするつもりで新しいメソッドを定義してしまうというミスがありますが、
@xuwei-k 確かに。強いて言うと、`@Override`を入れ忘れると気づかずオーバーライド問題は発生しますけど、せめて触れておくべきでした……。

2022-08-03 01:47 UTC, kmizu commented on src/class.md
> +例えば、Javaでは実装継承が1つだけに限定されています。
同じく良さそうです。

2022-08-03 01:48 UTC, kmizu commented on src/class.md
> +※「トレイト名」はここでは使われませんが、後で出てくるトレイトの節で説明を行います。
良さげです。

2022-08-03 01:50 UTC, kmizu requested changes
> このような仕組みのないJavaのような言語ではしばしば、気付かずに既存のメソッドをオーバーライドするつもりで新しいメソッドを定義してしまうというミスがありますが、

Javaには `@Override` アノテーションが（Java 5から）あって部分的には問題に対処できるので、

> このような仕組みのない言語ではしばしば、気付かずに既存のメソッドをオーバーライドするつもりで新しいメソッドを定義してしまうというミスがありますが、

としてもらえるでしょうか？それ以外はOKです。

2022-08-04 15:03 UTC, rinotc commented on src/class.md
> +このような仕組みのない言語ではしばしば、気付かずに既存のメソッドをオーバーライドするつもりで新しいメソッドを定義してしまうというミスがありますが、
@kmizu 
修正しました(｀･ω･´)ゞ

2022-08-07 10:49 UTC, merged